# Generated by Django 5.1.12 on 2026-01-10 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="votings/"),
                ),
                ("start_date", models.DateTimeField()),
                ("finish_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Voting",
                "verbose_name_plural": "Votings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Maintainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="voting.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintainer",
                "verbose_name_plural": "Maintainers",
            },
        ),
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_count",
                        to="voting.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Count",
                "verbose_name_plural": "Counts",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=20)),
                ("has_voted", models.BooleanField(default=False)),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("register", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_data",
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Data",
                "verbose_name_plural": "Users Data",
                "unique_together": {("id_voting", "rut")},
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="id_voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="voting.voting",
            ),
        ),
        migrations.CreateModel(
            name="VotingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=20)),
                ("mail", models.EmailField(max_length=254)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voting.subject"
                    ),
                ),
                (
                    "id_voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voting.voting"
                    ),
                ),
                (
                    "user_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.userdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voting Record",
                "verbose_name_plural": "Voting Records",
            },
        ),
    ]
