# Generated by Django 5.1.12 on 2026-01-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votingrecord",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="votingrecord",
            name="rut",
        ),
        migrations.RemoveField(
            model_name="votingrecord",
            name="user_data",
        ),
    ]
