# Generated by Django 5.1.12 on 2026-01-28 19:58

import django.db.models.deletion
from django.db import migrations, models


def crear_regiones(apps, schema_editor):
    """Crea las regiones de Chile"""
    Region = apps.get_model('voting', 'Region')
    
    regiones = [
        (1, 'Tarapacá'),
        (2, 'Antofagasta'),
        (3, 'Atacama'),
        (4, 'Coquimbo'),
        (5, 'Valparaíso'),
        (6, 'Libertador General Bernardo O\'Higgins'),
        (7, 'Maule'),
        (8, 'Biobío'),
        (9, 'La Araucanía'),
        (10, 'Los Lagos'),
        (11, 'Aysén del General Carlos Ibáñez del Campo'),
        (12, 'Magallanes y de la Antártica Chilena'),
        (13, 'Metropolitana de Santiago'),
        (14, 'Los Ríos'),
        (15, 'Arica y Parinacota'),
        (16, 'Ñuble'),
        (17, 'S/Region'),
    ]
    
    for region_id, nombre in regiones:
        Region.objects.create(id=region_id, name=nombre)


def eliminar_regiones(apps, schema_editor):
    """Elimina las regiones (rollback)"""
    Region = apps.get_model('voting', 'Region')
    Region.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regiones",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(crear_regiones, eliminar_regiones),
        migrations.AddField(
            model_name="voting",
            name="id_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="votings",
                to="voting.region",
            ),
        ),
    ]
