# Generated by Django 5.1.12 on 2026-01-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_region_voting_id_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Militante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Militante",
                "verbose_name_plural": "Militantes",
            },
        ),
        migrations.CreateModel(
            name="MilitanteRegistrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=20)),
                ("mail", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Militante Registration Token",
                "verbose_name_plural": "Militante Registration Tokens",
            },
        ),
        migrations.CreateModel(
            name="MilitantePasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "militante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to="voting.militante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Militante Password Reset Token",
                "verbose_name_plural": "Militante Password Reset Tokens",
            },
        ),
    ]
