# Generated by Django 5.1.12 on 2026-01-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0005_militante_militanteregistrationtoken_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voting",
            name="is_active",
        ),
    ]
