# Generated by Django 5.1.12 on 2026-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0006_remove_voting_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="voted_at",
        ),
        migrations.RemoveField(
            model_name="votingrecord",
            name="voted_at",
        ),
    ]
