# Generated by Django 5.1.12 on 2026-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0007_remove_timestamps_for_vote_anonymity"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingrecord",
            name="integrity_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
