# Generated by Django 5.1.12 on 2026-03-10 16:29

from django.db import migrations, models


# SQL para MariaDB/MySQL
# Los triggers impiden UPDATE y DELETE en la tabla de registros de votos
# a nivel de motor de base de datos, sin importar qué cliente intente hacerlo.

TRIGGER_BLOCK_UPDATE = """
CREATE TRIGGER trg_votingrecord_block_update
BEFORE UPDATE ON voting_votingrecord
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Los registros de votos son inmutables: UPDATE no permitido.';
END
"""

TRIGGER_BLOCK_DELETE = """
CREATE TRIGGER trg_votingrecord_block_delete
BEFORE DELETE ON voting_votingrecord
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Los registros de votos son inmutables: DELETE no permitido.';
END
"""

TRIGGER_BLOCK_UPDATE_COUNT = """
CREATE TRIGGER trg_count_block_update
BEFORE UPDATE ON voting_count
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'El contador de votos es de solo lectura: UPDATE no permitido.';
END
"""

DROP_TRIGGER_UPDATE = "DROP TRIGGER IF EXISTS trg_votingrecord_block_update"
DROP_TRIGGER_DELETE = "DROP TRIGGER IF EXISTS trg_votingrecord_block_delete"
DROP_TRIGGER_UPDATE_COUNT = "DROP TRIGGER IF EXISTS trg_count_block_update"


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_add_integrity_hash_to_votingrecord"),
    ]

    operations = [
        # Agregar campo chain_hash al modelo VotingRecord
        migrations.AddField(
            model_name='votingrecord',
            name='chain_hash',
            field=models.CharField(
                blank=True,
                max_length=64,
                help_text='Hash encadenado con el voto anterior de esta votación',
            ),
        ),

        # Trigger: bloquear UPDATE en voting_votingrecord
        migrations.RunSQL(
            sql=TRIGGER_BLOCK_UPDATE,
            reverse_sql=DROP_TRIGGER_UPDATE,
        ),

        # Trigger: bloquear DELETE en voting_votingrecord
        migrations.RunSQL(
            sql=TRIGGER_BLOCK_DELETE,
            reverse_sql=DROP_TRIGGER_DELETE,
        ),

        # Trigger: bloquear UPDATE en voting_count
        migrations.RunSQL(
            sql=TRIGGER_BLOCK_UPDATE_COUNT,
            reverse_sql=DROP_TRIGGER_UPDATE_COUNT,
        ),
    ]
