# Generated by Django 5.1.12 on 2026-03-27

from django.db import migrations


TRIGGER_BLOCK_DELETE_UNLESS_AUTHORIZED = """
CREATE TRIGGER trg_votingrecord_block_delete
BEFORE DELETE ON voting_votingrecord
FOR EACH ROW
BEGIN
    IF COALESCE(@allow_votingrecord_delete, 0) <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Los registros de votos son inmutables: DELETE no permitido sin token válido.';
    END IF;
END
"""

TRIGGER_ALLOW_COUNT_ONLY_PLUS_ONE = """
CREATE TRIGGER trg_count_block_update
BEFORE UPDATE ON voting_count
FOR EACH ROW
BEGIN
    IF NOT (NEW.id_subject_id = OLD.id_subject_id AND NEW.number = OLD.number + 1) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'El contador de votos solo permite incrementos de +1.';
    END IF;
END
"""

DROP_TRIGGER_DELETE = "DROP TRIGGER IF EXISTS trg_votingrecord_block_delete"
DROP_TRIGGER_UPDATE_COUNT = "DROP TRIGGER IF EXISTS trg_count_block_update"

TRIGGER_BLOCK_DELETE_PREVIOUS = """
CREATE TRIGGER trg_votingrecord_block_delete
BEFORE DELETE ON voting_votingrecord
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Los registros de votos son inmutables: DELETE no permitido.';
END
"""

TRIGGER_BLOCK_UPDATE_COUNT_PREVIOUS = """
CREATE TRIGGER trg_count_block_update
BEFORE UPDATE ON voting_count
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'El contador de votos es de solo lectura: UPDATE no permitido.';
END
"""


def _is_mysql(schema_editor):
    return schema_editor.connection.vendor == 'mysql'


def replace_delete_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_DELETE)
    schema_editor.execute(TRIGGER_BLOCK_DELETE_UNLESS_AUTHORIZED)


def restore_delete_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_DELETE)
    schema_editor.execute(TRIGGER_BLOCK_DELETE_PREVIOUS)


def replace_count_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_UPDATE_COUNT)
    schema_editor.execute(TRIGGER_ALLOW_COUNT_ONLY_PLUS_ONE)


def restore_count_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_UPDATE_COUNT)
    schema_editor.execute(TRIGGER_BLOCK_UPDATE_COUNT_PREVIOUS)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("voting", "0009_add_chain_hash_and_triggers"),
    ]

    operations = [
        migrations.RunPython(replace_delete_trigger, restore_delete_trigger),
        migrations.RunPython(replace_count_trigger, restore_count_trigger),
    ]
