# Generated by Django 5.1.12 on 2026-03-27

from django.db import migrations


TRIGGER_BLOCK_UPDATE_UNLESS_AUTHORIZED = """
CREATE TRIGGER trg_votingrecord_block_update
BEFORE UPDATE ON voting_votingrecord
FOR EACH ROW
BEGIN
    IF COALESCE(@allow_votingrecord_update, 0) <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Los registros de votos son inmutables: UPDATE no permitido.';
    END IF;
END
"""

TRIGGER_BLOCK_UPDATE_PREVIOUS = """
CREATE TRIGGER trg_votingrecord_block_update
BEFORE UPDATE ON voting_votingrecord
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Los registros de votos son inmutables: UPDATE no permitido.';
END
"""

DROP_TRIGGER_UPDATE = "DROP TRIGGER IF EXISTS trg_votingrecord_block_update"


def _is_mysql(schema_editor):
    return schema_editor.connection.vendor == 'mysql'


def replace_update_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_UPDATE)
    schema_editor.execute(TRIGGER_BLOCK_UPDATE_UNLESS_AUTHORIZED)


def restore_update_trigger(apps, schema_editor):
    if not _is_mysql(schema_editor):
        return
    schema_editor.execute(DROP_TRIGGER_UPDATE)
    schema_editor.execute(TRIGGER_BLOCK_UPDATE_PREVIOUS)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("voting", "0010_harden_delete_and_count_triggers"),
    ]

    operations = [
        migrations.RunPython(replace_update_trigger, restore_update_trigger),
    ]
