# Generated by Django 5.1.12 on 2026-03-27 16:54

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('voting', 'Role')
    roles = ["Administrador", "Auditor"]
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


def remove_initial_roles(apps, schema_editor):
    Role = apps.get_model('voting', 'Role')
    Role.objects.filter(name__in=["Administrador", "Auditor"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_add_militante_insert_trigger"),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, remove_initial_roles),
    ]
