# Generated by Django 5.2 on 2026-04-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0014_make_militante_token_expires_at_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("VOTANTES", "Carga de Votantes"),
                            ("REGISTRO_MILITANTES", "Invitación a Militantes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("emails_sent", models.IntegerField(default=0)),
                ("emails_failed", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maintainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.maintainer",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Upload Log",
                "verbose_name_plural": "Data Upload Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
