# Generated by Django 5.2 on 2026-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0015_datauploadlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("contador", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Count",
                "verbose_name_plural": "API Counts",
                "db_table": "count",
            },
        ),
        migrations.AlterField(
            model_name="datauploadlog",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("VOTANTES", "Carga de Votantes"),
                    ("REGISTRO_MILITANTES", "Envío de Correos a Militantes"),
                ],
                max_length=50,
            ),
        ),
    ]
