# Generated by Django 5.2 on 2026-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0016_apicounter_alter_datauploadlog_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="start_reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
