# Generated by Django 5.2 on 2026-06-25 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0017_voting_start_reminder_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("UPCOMING_VOTING", "Votación Próxima (Militante)"),
                            (
                                "UPCOMING_VOTING_UNREGISTERED",
                                "Votación Próxima (No Registrado)",
                            ),
                            ("REGISTRO_MILITANTE", "Invitación Registro Militante"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=255)),
                ("base_url", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.militanteregistrationtoken",
                    ),
                ),
                (
                    "upload_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to="voting.datauploadlog",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Queue Item",
                "verbose_name_plural": "Email Queue Items",
                "ordering": ["created_at"],
            },
        ),
    ]
