# Generated by Django 5.2 on 2026-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0018_emailqueueitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="militanteregistrationtoken",
            name="resent",
            field=models.BooleanField(default=False),
        ),
    ]
