# Generated by Django 5.2 on 2026-06-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0019_militanteregistrationtoken_resent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datauploadlog",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("VOTANTES", "Carga de Votantes"),
                    ("REGISTRO_MILITANTES", "Envío de Correos a Militantes"),
                    ("START_REMINDER", "Envío Recordatorio Votación Activa"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="emailqueueitem",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("UPCOMING_VOTING", "Votación Próxima (Militante)"),
                    (
                        "UPCOMING_VOTING_UNREGISTERED",
                        "Votación Próxima (No Registrado)",
                    ),
                    ("REGISTRO_MILITANTE", "Invitación Registro Militante"),
                    ("VOTING_REMINDER", "Votación Activa / En Curso"),
                ],
                max_length=50,
            ),
        ),
    ]
