# Generated by Django 5.2 on 2026-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0021_document_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
