# Generated by Django 5.2 on 2026-07-08 23:07

from django.db import migrations, models


def create_empleado_role(apps, schema_editor):
    Role = apps.get_model('voting', 'Role')
    Role.objects.get_or_create(name='Empleado')


def remove_empleado_role(apps, schema_editor):
    Role = apps.get_model('voting', 'Role')
    Role.objects.filter(name='Empleado').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0022_documentsection_is_active"),
    ]

    operations = [
        migrations.RunPython(create_empleado_role, remove_empleado_role),
        migrations.AddField(
            model_name="maintainer",
            name="perm_gestion_documentos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="maintainer",
            name="perm_gestionar_maintainers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintainer",
            name="perm_gestionar_usuarios",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="maintainer",
            name="perm_gestionar_votaciones",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="maintainer",
            name="perm_ver_estadisticas",
            field=models.BooleanField(default=True),
        ),
    ]
