# Generated by Django 5.2 on 2026-07-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0024_faq_maintainer_perm_gestionar_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="militante",
            name="region",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="militanteregistrationtoken",
            name="region",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datauploadlog",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("VOTANTES", "Carga de Votantes"),
                    ("REGISTRO_MILITANTES", "Actualizar Padrón"),
                    ("START_REMINDER", "Envío Recordatorio Votación Activa"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="militanteregistrationtoken",
            name="mail",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="militanteregistrationtoken",
            name="nombre",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
