# Generated by Django 5.2 on 2026-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0025_militante_region_militanteregistrationtoken_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("public_token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Access Key",
                "verbose_name_plural": "Access Keys",
            },
        ),
        migrations.AddField(
            model_name="voting",
            name="report_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
