# Generated by Django 5.2 on 2026-07-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0026_accesskey_voting_report_unlocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityBlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.maintainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Bloqueada",
                "verbose_name_plural": "IPs Bloqueadas",
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_FAILED", "Login Fallido"),
                            ("LOGIN_SUCCESS", "Login Exitoso"),
                            ("RATE_LIMITED", "Rate Limited"),
                            ("CHAIN_INTEGRITY_OK", "Cadena Íntegra"),
                            ("CHAIN_INTEGRITY_FAIL", "Cadena Alterada"),
                            ("VOTE_ANOMALY", "Anomalía de Voto"),
                            ("PASSWORD_RESET", "Reset Contraseña"),
                            ("IP_BLOCKED", "IP Bloqueada"),
                            ("IP_UNBLOCKED", "IP Desbloqueada"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField()),
                (
                    "militante_rut",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "maintainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.maintainer",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Seguridad",
                "verbose_name_plural": "Eventos de Seguridad",
                "ordering": ["-created_at"],
            },
        ),
    ]
