# Generated by Django 5.2 on 2026-07-29 17:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0027_securityblockedip_securityevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingrecord",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="votingrecord",
            name="chain_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash encadenado con el voto anterior de esta votación",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="votingrecord",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
