# Generated by Django 5.2 on 2026-07-29 17:25

import uuid
from django.db import migrations, models

TRIGGER_BLOCK_UPDATE = """
CREATE TRIGGER trg_votingrecord_block_update
BEFORE UPDATE ON voting_votingrecord
FOR EACH ROW
BEGIN
    IF COALESCE(@allow_votingrecord_update, 0) <> 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Los registros de votos son inmutables: UPDATE no permitido.';
    END IF;
END
"""

TRIGGER_BLOCK_DELETE = """
CREATE TRIGGER trg_votingrecord_block_delete
BEFORE DELETE ON voting_votingrecord
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Los registros de votos son inmutables: DELETE no permitido.';
END
"""


def convert_id_to_uuid(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    VotingRecord = apps.get_model("voting", "VotingRecord")

    if vendor == "mysql":
        with connection.cursor() as cursor:
            # 1. Clean up residual created_at column if present in MySQL from failed previous attempt
            cursor.execute("SHOW COLUMNS FROM voting_votingrecord LIKE 'created_at';")
            if cursor.fetchone():
                cursor.execute("ALTER TABLE voting_votingrecord DROP COLUMN created_at;")

            # 2. Clean up residual previous_hash column if present in MySQL from failed previous attempt
            cursor.execute("SHOW COLUMNS FROM voting_votingrecord LIKE 'previous_hash';")
            if cursor.fetchone():
                cursor.execute("ALTER TABLE voting_votingrecord DROP COLUMN previous_hash;")

            # 3. Clean up residual unique index on chain_hash if present
            cursor.execute(
                "SHOW INDEX FROM voting_votingrecord WHERE Key_name = 'voting_votingrecord_chain_hash_c993d4b3_uniq';"
            )
            if cursor.fetchone():
                cursor.execute(
                    "ALTER TABLE voting_votingrecord DROP INDEX voting_votingrecord_chain_hash_c993d4b3_uniq;"
                )

            # 4. Check id column type
            cursor.execute("SHOW COLUMNS FROM voting_votingrecord LIKE 'id';")
            col_info = cursor.fetchone()
            col_type = col_info[1].lower() if col_info else ""

            if "bigint" in col_type or "int" in col_type:
                # Temporarily drop triggers that block UPDATE/DELETE
                cursor.execute("DROP TRIGGER IF EXISTS trg_votingrecord_block_update;")
                cursor.execute("DROP TRIGGER IF EXISTS trg_votingrecord_block_delete;")

                # Determine UUID db column type
                uuid_db_type = models.UUIDField().db_type(connection)

                # Add new temporary UUID column
                cursor.execute(f"ALTER TABLE voting_votingrecord ADD COLUMN new_id {uuid_db_type} NULL;")

                # Populate new_id for existing rows
                cursor.execute("SELECT id FROM voting_votingrecord;")
                rows = cursor.fetchall()
                for (old_id,) in rows:
                    cursor.execute(
                        "UPDATE voting_votingrecord SET new_id = %s WHERE id = %s;",
                        [str(uuid.uuid4()), old_id],
                    )

                # Modify id column to remove AUTO_INCREMENT
                cursor.execute("ALTER TABLE voting_votingrecord MODIFY id bigint NOT NULL;")

                # Drop primary key constraint
                cursor.execute("ALTER TABLE voting_votingrecord DROP PRIMARY KEY;")

                # Drop old id column
                cursor.execute("ALTER TABLE voting_votingrecord DROP COLUMN id;")

                # Rename new_id to id and set primary key
                cursor.execute(
                    f"ALTER TABLE voting_votingrecord CHANGE new_id id {uuid_db_type} NOT NULL PRIMARY KEY;"
                )

                # Re-create triggers
                cursor.execute(TRIGGER_BLOCK_UPDATE)
                cursor.execute(TRIGGER_BLOCK_DELETE)

    elif vendor == "sqlite":
        old_field = VotingRecord._meta.get_field("id")
        new_field = models.UUIDField(
            default=uuid.uuid4, editable=False, primary_key=True, serialize=False
        )
        new_field.model = VotingRecord
        new_field.set_attributes_from_name("id")
        schema_editor.alter_field(VotingRecord, old_field, new_field)


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0027_securityblockedip_securityevent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_id_to_uuid, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="votingrecord",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="votingrecord",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hash del voto anterior en la cadena",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="votingrecord",
            name="chain_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash encadenado único del voto",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]


